### ISSUE TITLE
Sith meets Storm Trooper interaction

### ISSUE THREAD

**Issue by Lutonite** [heig-lherman/mcr-project#10]
- Teleport storm trooper to one random coordinate in a list

**Comment by Lutonite** [comment]
![vanishTeleportation](https://github.com/heig-lherman/mcr-project/assets/21953109/9d4af1f6-4070-4914-847e-a4e728bd83a3)

Nice-to-have: on peut éventuellement utiliser cette spritesheet pour l'animation de TP (mais dans ce cas faudrait d'abord finir l'animation avant de faire la vrai "téléportation")

**Comment by DrC0okie** [comment]
Done
